package com.smartlogis.userservice.domain.exception;

import org.springframework.http.HttpStatus;

import com.smartlogis.common.exception.MessageCode;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum UserMessageCode implements MessageCode {
	USER_NOT_FOUND("USER.USER_NOT_FOUND", HttpStatus.NOT_FOUND),
	MISMATCH_PASSWORD_CONFIRM("USER.MISMATCH_PASSWORD_CONFIRM", HttpStatus.BAD_REQUEST),
    INVALID_ROLE("USER.INVALID_ROLE", HttpStatus.BAD_REQUEST),
	INVALID_ORGANIZATION_TYPE("USER.INVALID_ORGANIZATION_TYPE", HttpStatus.BAD_REQUEST),
	INVALID_ORGANIZATION_ROLE("USER.INVALID_ORGANIZATION_ROLE", HttpStatus.BAD_REQUEST),
	INVALID_STATUS("USER.INVALID_STATUS", HttpStatus.BAD_REQUEST),
	INVALID_STATUS_CHANGE("USER.INVALID_STATUS_CHANGE", HttpStatus.BAD_REQUEST),
	USER_ALREADY_REGISTERED("USER.USER_ALREADY_REGISTERED", HttpStatus.CONFLICT),
	USER_ALREADY_PENDING("USER.USER_ALREADY_PENDING", HttpStatus.CONFLICT),
	USER_NOT_APPROVED("USER.USER_NOT_APPROVED", HttpStatus.UNAUTHORIZED),
	ORGANIZATION_ACCESS_DENIED("USER.ORGANIZATION_ACCESS_DENIED", HttpStatus.UNAUTHORIZED),
	ACCESS_DENIED("USER.ACCESS_DENIED", HttpStatus.UNAUTHORIZED),
	;

    private final String code;
    private final HttpStatus status;
}
